require('colorscheme')
require('settings')
require('keybindings')
require('plugins')
require('utils')
require('plugins/compe')
require('plugins/treesitter')
require('plugins/lspConfig')
require('plugins/autopair')
require('plugins/colorizer')
require('plugins/ranger')
require('plugins/telescope')
require('plugins/nvim-tree')

