require('settings')
require('plugins')
require('keybindings')
require('utils')
require('plugins/treesitter')
require('plugins/compe')
require('plugins/lspConfig')
require('plugins/nullLs')
require('plugins/autopair')
require('plugins/colorizer')
require('plugins/telescope')
require('plugins/nvimTree')
-- using lualine instead of galaxyline
require('plugins/lualine')
require('plugins/discord')
-- require('plugins/indent')
-- require('plugins/gitsigns')
require('colorscheme')
